EMOTES = {
    "1": "dance-swagbounce", "2": "dance-duckwalk", "3": "dance-pennywise",
    "4": "idle-floorsleeping", "5": "sit-idle-laidBack", "6": "emote-ghost-idle", 
    "7": "idle-loop-annoyed", "8": "dance-touch", "9": "dance-jinglebell", 
    "10": "idle-space", "11": "dance-metal", "12": "emoji-flex", 
    "13": "dance-orangejustice", "14": "emote-shy2", "15": "emote-blowkisses", 
    "16": "emote-stargazer", "17": "emote-knocking-screen", "18": "emote-curtsy", 
    "19": "emote-slap", "20": "idle_singing", "21": "idle-dance-swinging", 
    "22": "dance-kawai", "23": "emote-pose9", "24": "dance-tiktok9", 
    "25": "dance-floss", "26": "dance-breakdance", "27": "dance-wild", 
    "28": "dance-hipshake", "29": "dance-griddy", "30": "emote-shrink", 
    "31": "dance-spiritual", "32": "dance-martial-artist", "33": "emote-hero", 
    "34": "dance-tiktok2", "35": "dance-popularvibe", "36": "emote-headball", 
    "37": "dance-true-heart", "38": "dance-mine", "39": "dance-robotic",
    "40": "emote-graceful", "41": "emote-meditate-idle", "42": "emote-frollicking", 
    "43": "dance-ballet", "44": "dance-woah", "45": "dance-shuffle", 
    "46": "emote-frog", "47": "emoji-lying", "48": "emote-laughing2", 
    "49": "emote-boxer", "50": "dance-tiktok10", "51": "emote-attention", 
    "52": "emote-dab", "53": "timejump", "54": "emote-puppet", 
    "55": "dance-aerobics", "56": "idle-guitar", "57": "idle-dance-tiktok7", 
    "58": "dance-tiktok11", "59": "idle-loop-tapdance", "60": "emote-pose10", 
    "61": "emoji-scared", "62": "emoji-arrogance", "63": "dance-wrong", 
    "64": "emoji-halo", "65": "dance-anime", "66": "emote-hyped", 
    "67": "emote-boo", "68": "emote-trampoline", "69": "emoji-ghost", 
    "70": "emote-float", "71": "emote-sleigh", "72": "dance-cheerleader", 
    "73": "emote-ninjarun", "74": "emote-gangnam", "75": "emote-snake", 
    "76": "dance-pinguin", "77": "idle-loop-aerics", "78": "emote-howl", 
    "79": "emote-launch", "80": "dance-creepypuppet", "81": "emote-gravity", 
    "82": "emote-confused", "83": "emote-creepycute", "84": "dance-smoothwalk", 
    "85": "idle-nervous", "86": "emote-gordonshuffle", "87": "emote-rofl", 
    "88": "dance-icecream", "89": "emote-celebrate", "90": "emote-panic", 
    "91": "emote-punkguitar", "92": "dance-singleladies", "93": "emoji-punch", 
    "94": "dance-shoppingcart", "95": "idle-dance-tiktok4", "96": "emote-nightfever", 
    "97": "emote-snowangel", "98": "emote-headblowup", "99": "emote-roll", 
    "100": "sit-open",
    "101": "emote-superrun", "102": "emote-disappear", "103": "idle_layingdown2", 
    "104": "idle-uwu", "105": "emote-harlemshake", "106": "dance-blackpink", 
    "107": "dance-employee", "108": "emote-cute", "109": "dance-tiktok14", 
    "110": "dance-russian", "111": "emote-handstand", "112": "emote-elbowbump", 
    "113": "idle-floating", "114": "emoji-mind-blown", "115": "idle_zombie", 
    "116": "emote-disco", "117": "emote-jumpb", "118": "emote-heartshape", 
    "119": "emote-judochop", "120": "emote-levelup", "121": "emote-peace", 
    "122": "emote-suckthumb", "123": "emote-think", "124": "idle-dance-headbobbing",
    "125": "idle-loop-tired", "126": "emoji-crying", "127": "emoji-dizzy", 
    "128": "emoji-pray", "129": "emote-exasperated", "130": "idle-sad", 
    "131": "emote-deathdrop", "132": "emote-hot", "133": "emote-hug", 
    "134": "idle-loop-sad", "135": "idle-lookup", "136": "idle-posh", 
    "137": "emote-wings", "138": "emoji-there", "139": "emote-superpunch", 
    "140": "idle-sleep", "141": "dance-weird", "142": "emote-fainting", 
    "143": "emote-monster_fail", "144": "idle-hero", "145": "dance-handsup", 
    "146": "emote-fail2", "147": "emote-ropepull", "148": "emote-bow", 
    "149": "emote-model", "150": "emote-splitsdrop", "151": "emoji-sick", 
    "152": "emote-embarrassed", "153": "emote-proposing", "154": "idle-enthusiastic", 
    "155": "emote-cold", "156": "emote-telekinesis", "157": "emoji-hadoken", 
    "158": "emoji-sneeze", "159": "emote-fail1", "160": "emoji-naughty", 
    "161": "emote-hugyourself", "162": "emote-theatrical", "163": "emote-greedy", 
    "164": "emote-baseball",

    # --- Vos nouvelles émotes numériques de 165 à 175 ---
    "165": "emote-sumo",
    "166": "emote-death2",
    "167": "emoji-smirking",
    "168": "dance-voguehands",
    "169": "emoji-eyeroll",
    "170": "emoji-give-up",
    "171": "emote-bunnyhop",
    "172": "emote-exasperatedb",
    "173": "idle-loop-happy",
    "174": "emote-heartfingers",
    "175": "emote-collab-photo-left"
}
